### ISSUE TITLE
SSH private key deleted accidentally 

### ISSUE THREAD

**Issue by ali-tm-amin** [elifesciences/observer#150]
# Description

The error message here when you ssh `ssh: connect to host 34.201.187.7 port 22: Operation timed out
ERROR - threadbare.operations - Fatal error: local() encountered an error (return code 255) while executing '/bin/bash -l -c "ssh -o \\"ConnectionAttempts 3\\" elife@34.201.187.7 -i ~/.ssh/id_rsa"'
WARNING - cfn - local() encountered an error (return code 255) while executing '/bin/bash -l -c "ssh -o \\"ConnectionAttempts 3\\" elife@34.201.187.7 -i ~/.ssh/id_rsa"'`

To avoid losing data on the instance follow these steps below
# Subtask

- [ ] To confirm that a root volume is configured to persist using the Amazon EC2 console
 

```[tasklist]
### Tasks
- [ ] Open the Amazon EC2 console at https://console.aws.amazon.com/ec2/.
- [ ] In the navigation pane, choose Instances and then select the instance.
- [ ] In the Storage tab, under Block devices, locate the entry for the root volume. If Delete on termination is No, the volume is configured to persist.
```

- [ ] Stopping and restarting the instance changes the public IP address of your instance. It's a best practice to use an [Elastic IP address](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) instead of a public IP address when routing external traffic to your instance.

- [ ] Create a new key pair

```[tasklist]
### Tasks
- [ ] Step 1: Create a new key pair
- [ ] Step 2: Get information about the original instance and its root volume
- [ ] Step 3: Stop the original instance
- [ ] Step 4: Launch a temporary instance
- [ ] Step 5: Detach the root volume from the original instance and attach it to the temporary instance
- [ ] Step 6: Add the new public key to authorized_keys on the original volume mounted to the temporary instance
- [ ] Step 7: Unmount and detach the original volume from the temporary instance, and reattach it to the original instance
- [ ] Step 8: Connect to the original instance using the new key pair
- [ ] Step 9: Clean up
```

# Definition of Done

- [ ] Can SSH the instance successfully

**Comment by ali-tm-amin** [comment]
The methods above did not solve the issue, and the node couldn't be reproduced through [upgrading the os instance](https://github.com/elifesciences/builder/blob/master/docs/playbooks/upgrade-os-instances.md ) as tried with @giorgiosironi for the elife-metrics as both are having the same issue of using outdated image ID (AMIs). The only solution is to containerise them and deploy them to the cluster. Now the observer is containerised on a new branch called `containerise` and will be deployed soon.

I have created a snapshot of the EBS volume for this `observer--prod` node on AWS and the snapshot ID is 
`snap-08a88ac774e8a8c22`
